version: '3.8'

networks:
  hackaton:

volumes:
  openfga:

services:
  migrate:
    image: openfga/openfga:latest
    container_name: migrate
    command: migrate
    user: nonroot
    environment:
      - OPENFGA_DATASTORE_ENGINE=sqlite
      - OPENFGA_DATASTORE_URI=file:/home/nonroot/openfga.db
    networks:
      - hackaton
    volumes:
      - openfga:/home/nonroot

  openfga:
    depends_on:
      migrate:
        condition: service_completed_successfully
    image: openfga/openfga:latest
    container_name: openfga
    user: root
    environment:
      - OPENFGA_DATASTORE_ENGINE=sqlite
      - OPENFGA_DATASTORE_URI=file:/home/nonroot/openfga.db
      - OPENFGA_LOG_FORMAT=json
      - OPENFGA_HTTP_CORS_ALLOWED_ORIGINS=http://localhost:*,http://127.0.0.1:*,https://play.fga.dev
    command:  run
    networks:
      - hackaton
    volumes:
      - openfga:/home/nonroot
    ports:
      # Needed for the http server
      - "8080:8080"
      # Needed for the grpc server (if used)
      - "8081:8081"
      # Needed for the playground (Do not enable in prod!)
      - "3000:3000"

  dotnet-sample-api:
    container_name: dotnet-sample-api
    image: dotnet-sample-api:latest
    build:
      context: ..
      dockerfile: dotnet/sample-api/aspnetcoreapp/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5116:8080"
    networks:
      - hackaton